# array 인덱싱 이해하기
기본 인덱싱

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

np.int64(5)

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[-1]

np.int64(9)

In [8]:
x = arr[0:9]
y = arr[-1]

In [9]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
y

np.int64(9)

In [11]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [12]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [13]:
arr[5:8] = [5,6,7]

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2차원 array

In [17]:
arr2 = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])

arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
arr2.shape

(4, 4)

In [20]:
# 2행의 전체값 가져오기
arr2[2, :]

array([ 9, 10, 11, 12])

In [21]:
arr2[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# 전체 행을 가져오되, 열값은 마지막만 가져오기
arr2[:, -1]

array([ 4,  8, 12, 16])

In [27]:
# 3행의 2열값 가져오기
arr2[3,2]

np.int64(15)

In [28]:
# 0~1행까지, 1~2열까지의 값만 가져오기
arr2[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [29]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# 불리언 인덱싱

In [36]:
names = np.array(['charles', 'hyunsu', 'hayoung', 'charles', 'hayoung', 'hyunsu', 'hyunsu'])
data = np.random.randn(7, 4)

In [37]:
names

array(['charles', 'hyunsu', 'hayoung', 'charles', 'hayoung', 'hyunsu',
       'hyunsu'], dtype='<U7')

In [38]:
data

array([[ 0.25409737,  0.03304546, -1.62540104,  0.48975826],
       [ 0.00806456, -0.41497919,  0.64603388,  0.1849573 ],
       [ 0.1788861 , -0.3153483 ,  0.16360796,  1.40826719],
       [-0.94929878,  1.22406522, -1.52966985,  0.83319767],
       [ 1.31415595, -0.1889869 ,  0.8016009 ,  2.64324352],
       [ 0.24132067,  0.31901423, -1.03203135, -0.61915645],
       [ 0.05749089,  0.23144446,  2.43631424, -0.59039945]])

In [39]:
# charles 값만 확인하기
names == 'charles'

array([ True, False, False,  True, False, False, False])

In [ ]:
# charles의 마스크(인덱스)를 이용해서 data array를 인덱싱하기
data[names == 'charles', :]

array([[ 0.25409737,  0.03304546, -1.62540104,  0.48975826],
       [-0.94929878,  1.22406522, -1.52966985,  0.83319767]])

In [44]:
names == 'hyunsu'

array([False,  True, False, False, False,  True,  True])

In [ ]:
data[names == 'hyunsu', :]

array([[ 0.00806456, -0.41497919,  0.64603388,  0.1849573 ],
       [ 0.24132067,  0.31901423, -1.03203135, -0.61915645],
       [ 0.05749089,  0.23144446,  2.43631424, -0.59039945]])

In [45]:
# charles와 hyunsu의 마스크를 이용하여 data array 인덱싱하기
data[(names == 'charles') | (names == 'hyunsu'), :]

array([[ 0.25409737,  0.03304546, -1.62540104,  0.48975826],
       [ 0.00806456, -0.41497919,  0.64603388,  0.1849573 ],
       [-0.94929878,  1.22406522, -1.52966985,  0.83319767],
       [ 0.24132067,  0.31901423, -1.03203135, -0.61915645],
       [ 0.05749089,  0.23144446,  2.43631424, -0.59039945]])

In [46]:
data[:, 3] < 0

array([False, False, False, False, False,  True,  True])

In [47]:
data[data[:,3] < 0, :] = 0
data

array([[ 0.25409737,  0.03304546, -1.62540104,  0.48975826],
       [ 0.00806456, -0.41497919,  0.64603388,  0.1849573 ],
       [ 0.1788861 , -0.3153483 ,  0.16360796,  1.40826719],
       [-0.94929878,  1.22406522, -1.52966985,  0.83319767],
       [ 1.31415595, -0.1889869 ,  0.8016009 ,  2.64324352],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])