In [1]:
import numpy as np

In [6]:
data = [6,7.5,8,0,1]

In [7]:
arr1 = np.array(data)

In [8]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
arr1.shape

(5,)

In [11]:
arr = np.array([2,3,4])
arr

array([2, 3, 4])

# 2차원 array

In [12]:
data2 = ([1,2,3,4],[5,6,7,8])

In [13]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.shape

(2, 4)

# zeros(), ones(), arange() 함수 기능

In [15]:
# 0으로 된 array를 만든다
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
# 1로 된 array를 만든다
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
# 연속된 수로 array를 만든다
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 데이터 타입

**numpy에서 사용 가능한 데이터형(dtype) 정리**

- **int8, int16, int32, int64** : 부호가 있는 [8, 16, 32, 64]비트 정수

- **uint8, uint16, uint32, uint64** : 부호가 없는 [8, 16, 32, 64]비트 정수

- **float16, float32, float64, float128** : [16, 32, 64, 128]비트 실수

- **complex64, complex128, complex256** : [64, 128, 256]비트 복소수

- **bool** : 불리언 (True 또는 False)

- **object** : Python 오브젝트 형

- **string_** : 문자열

- **unicode_** : 유니코드 문자열

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [23]:
arr = np.array([1,2,3,4,5], dtype=np.int64)
arr

array([1, 2, 3, 4, 5])

In [24]:
# 기존의 타입을 변경하기 astype()
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [25]:
float_arr.dtype

dtype('float64')

# numpy 계산 조건
## 타입과 개수가 맞을것

In [28]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.float64)

In [29]:
arr2 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [30]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
# 연산(+) 2차원에서 같은 위치의 성분끼리 연산이 된다. (모든 연산이 같음)
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [36]:
# 각 성분에 일반 숫자를 적용하여 연산하기
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [37]:
# 제곱근
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [38]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])