In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# square
np.square(arr)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
# Log
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [5]:
x = np.random.randn(8)
y = np.random.randn(8)

In [6]:
x

array([-0.64812141,  1.97242723, -0.01905932,  0.21235788, -1.22474289,
       -0.69514114,  0.75595655, -1.74932657])

In [7]:
y

array([ 0.24873734, -1.52907014, -0.45641661,  1.57970238,  0.94512736,
       -0.55146401,  0.09884679, -1.10603162])

In [8]:
# x와 y의 위치값을 비교하여 maximum 수행
np.maximum(x,y)

array([ 0.24873734,  1.97242723, -0.01905932,  1.57970238,  0.94512736,
       -0.55146401,  0.75595655, -1.10603162])

In [9]:
arr = np.random.randn(5,4)
arr

array([[ 0.74121409,  0.88863934, -2.33625081,  0.31488864],
       [ 0.48856506,  0.38428226, -0.63349136,  0.89206862],
       [ 0.28365412, -0.99496829, -1.29217378,  0.41697655],
       [-0.32751261, -0.09234683, -1.14402213,  1.53904429],
       [ 0.97475502,  0.43344648,  2.12650582, -0.55418006]])

In [11]:
# arr 어레이와 모든 값에 대하여 sum 수행
arr.sum()

np.float64(2.109094414834683)

In [12]:
arr.mean()

np.float64(0.10545472074173415)

In [ ]:
# 열방향의 값들을 불러옴
arr.sum(axis=0)

array([ 2.16067568,  0.61905296, -3.27943226,  2.60879803])

In [14]:
arr.sum(axis=1)

array([-0.39150874,  1.13142457, -1.5865114 , -0.02483728,  2.98052726])

In [15]:
# 조건부 연산
arr > 0

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False, False, False,  True],
       [ True,  True,  True, False]])

In [18]:
# True 값에 대해서 sum을 수행
(arr > 0).sum()

np.int64(12)

In [20]:
arr = np.random.randn(8)
arr

array([ 0.14355916, -0.99742841, -0.20167462,  0.38435464, -0.44439134,
       -0.78720835, -0.52278749, -0.75892795])

In [ ]:
# 1차원 오름차순 정렬
np.sort(arr)

array([-0.99742841, -0.78720835, -0.75892795, -0.52278749, -0.44439134,
       -0.20167462,  0.14355916,  0.38435464])

In [ ]:
# 1차원 내림차순 정렬
np.sort(arr)[::-1]

array([ 0.38435464,  0.14355916, -0.20167462, -0.44439134, -0.52278749,
       -0.75892795, -0.78720835, -0.99742841])

In [23]:
# 2차원 오름차순 정렬
arr = np.random.randn(5,3)
arr

array([[ 1.0573413 , -0.72140535,  1.34293829],
       [ 1.3247703 ,  1.45819895,  0.49343887],
       [-0.81733597, -1.55877491, -0.3257037 ],
       [ 0.82923128, -0.25288189,  1.05122321],
       [-0.16923865,  1.8695462 ,  1.79996496]])

In [24]:
# 행 방향으로 열의 값을 오름차순 정렬
np.sort(arr, axis=0)

array([[-0.81733597, -1.55877491, -0.3257037 ],
       [-0.16923865, -0.72140535,  0.49343887],
       [ 0.82923128, -0.25288189,  1.05122321],
       [ 1.0573413 ,  1.45819895,  1.34293829],
       [ 1.3247703 ,  1.8695462 ,  1.79996496]])

In [25]:
# 열방향으로 행의 값을 오름차순 정렬
np.sort(arr, axis=1)

array([[-0.72140535,  1.0573413 ,  1.34293829],
       [ 0.49343887,  1.3247703 ,  1.45819895],
       [-1.55877491, -0.81733597, -0.3257037 ],
       [-0.25288189,  0.82923128,  1.05122321],
       [-0.16923865,  1.79996496,  1.8695462 ]])

In [26]:
# Large_arr 어레이가 정의가 되어 있을 때, 해당 array 상에서 상위 5%에 위치하는 값을 찾기
large_arr = np.random.randn(150)
large_arr

array([ 4.98357567e-02, -3.63461186e-01,  6.65254965e-01, -9.53003527e-01,
        5.23739958e-02,  2.17999451e+00, -3.42806744e-02,  2.35894728e-01,
        6.75877498e-01, -1.24891304e+00,  1.79645342e+00,  1.89739047e-01,
       -1.43842889e-01,  4.16492934e-01,  1.16878924e+00,  4.95019842e-01,
       -9.96320964e-01,  5.41833940e-01,  7.01629136e-01,  8.73872532e-01,
       -8.36436435e-01, -8.40073331e-01,  1.36730278e+00,  1.24787128e+00,
        5.88850903e-01,  2.37581121e+00,  6.92098818e-01, -3.18101097e-02,
       -6.18830070e-01,  1.38677546e+00,  1.03485121e+00,  7.85409528e-01,
        7.75197021e-01,  8.89771755e-01, -1.20687643e+00,  1.23701900e+00,
        1.74661890e+00,  3.79678930e-01, -3.19152976e-01, -1.22244590e+00,
        2.08087769e+00, -5.16801914e-01, -1.12835466e-01,  1.80879961e+00,
       -1.52668401e+00,  1.00290104e+00, -6.43427420e-01, -8.06960094e-01,
       -3.96385381e-01, -4.41360391e-01,  3.88788818e-03,  1.16050731e+00,
        8.62744501e-01, -

In [ ]:
# 내림차순 정렬
np.sort(large_arr)[::-1]

array([ 2.37581121e+00,  2.33717637e+00,  2.17999451e+00,  2.13990473e+00,
        2.08087769e+00,  2.06632179e+00,  2.03476639e+00,  1.97777513e+00,
        1.80879961e+00,  1.79645342e+00,  1.78635068e+00,  1.75467954e+00,
        1.74661890e+00,  1.49340902e+00,  1.40000520e+00,  1.38677546e+00,
        1.36730278e+00,  1.33752182e+00,  1.31447397e+00,  1.30568302e+00,
        1.26093983e+00,  1.24787128e+00,  1.23701900e+00,  1.20471270e+00,
        1.16878924e+00,  1.16050731e+00,  1.13621587e+00,  1.05657172e+00,
        1.04713770e+00,  1.03485121e+00,  1.00290104e+00,  9.86275524e-01,
        9.58947780e-01,  9.52764235e-01,  9.48565945e-01,  8.89771755e-01,
        8.80850511e-01,  8.76835213e-01,  8.73872532e-01,  8.62744501e-01,
        7.99839682e-01,  7.98405091e-01,  7.85409528e-01,  7.79348285e-01,
        7.75197021e-01,  7.51244022e-01,  7.01629136e-01,  7.00381240e-01,
        6.92098818e-01,  6.86954937e-01,  6.77267830e-01,  6.75877498e-01,
        6.65254965e-01,  

In [29]:
# 상위 5% 값 찾기(0.05 * 150)
np.sort(large_arr)[::-1][:int(0.05 * len(large_arr))] 

array([2.37581121, 2.33717637, 2.17999451, 2.13990473, 2.08087769,
       2.06632179, 2.03476639])

In [30]:
# unique 함수
names = np.array(['aa','bb','aa','cc','cc','aa','dd'])
ints = np.array([3,3,3,4,4,1,1,2,5,5,6,8])

In [31]:
np.unique(names)

array(['aa', 'bb', 'cc', 'dd'], dtype='<U2')

In [32]:
np.unique(ints)

array([1, 2, 3, 4, 5, 6, 8])